#!/usr/bin/env sh
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE ROLE "rep-user" NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT LOGIN REPLICATION NOBYPASSRLS PASSWORD 'rep-user';
EOSQL

